# Generated by Django 5.2.1 on 2025-05-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_airplanetype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
